const char *licenses =
        "Sftpgui\n"
        "=======\n"
        "MIT License\n"
        "\n"
        "Copyright (c) 2020 Allan Riordan Boll\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in all\n"
        "copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
        "SOFTWARE.\n"
        "\n"
        "\n"
        "libssh2\n"
        "=======\n"
        "/* Copyright (c) 2004-2007 Sara Golemon <sarag@libssh2.org>\n"
        " * Copyright (c) 2005,2006 Mikhail Gusarov <dottedmag@dottedmag.net>\n"
        " * Copyright (c) 2006-2007 The Written Word, Inc.\n"
        " * Copyright (c) 2007 Eli Fant <elifantu@mail.ru>\n"
        " * Copyright (c) 2009-2019 Daniel Stenberg\n"
        " * Copyright (C) 2008, 2009 Simon Josefsson\n"
        " * All rights reserved.\n"
        " *\n"
        " * Redistribution and use in source and binary forms,\n"
        " * with or without modification, are permitted provided\n"
        " * that the following conditions are met:\n"
        " *\n"
        " *   Redistributions of source code must retain the above\n"
        " *   copyright notice, this list of conditions and the\n"
        " *   following disclaimer.\n"
        " *\n"
        " *   Redistributions in binary form must reproduce the above\n"
        " *   copyright notice, this list of conditions and the following\n"
        " *   disclaimer in the documentation and/or other materials\n"
        " *   provided with the distribution.\n"
        " *\n"
        " *   Neither the name of the copyright holder nor the names\n"
        " *   of any other contributors may be used to endorse or\n"
        " *   promote products derived from this software without\n"
        " *   specific prior written permission.\n"
        " *\n"
        " * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND\n"
        " * CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES,\n"
        " * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES\n"
        " * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
        " * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR\n"
        " * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
        " * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
        " * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR\n"
        " * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\n"
        " * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,\n"
        " * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
        " * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE\n"
        " * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY\n"
        " * OF SUCH DAMAGE.\n"
        " */\n"
        "\n"
        "\n"
        "              wxWindows Library Licence, Version 3.1\n"
        "              ======================================\n"
        "\n"
        "Copyright (c) 1998-2005 Julian Smart, Robert Roebling et al\n"
        "\n"
        "Everyone is permitted to copy and distribute verbatim copies\n"
        "of this licence document, but changing it is not allowed.\n"
        "\n"
        "                     WXWINDOWS LIBRARY LICENCE\n"
        "   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n"
        "\n"
        "This library is free software; you can redistribute it and/or modify it\n"
        "under the terms of the GNU Library General Public Licence as published by\n"
        "the Free Software Foundation; either version 2 of the Licence, or (at your\n"
        "option) any later version.\n"
        "\n"
        "This library is distributed in the hope that it will be useful, but WITHOUT\n"
        "ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or\n"
        "FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Library General Public\n"
        "Licence for more details.\n"
        "\n"
        "You should have received a copy of the GNU Library General Public Licence\n"
        "along with this software, usually in a file named COPYING.LIB.  If not,\n"
        "write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth\n"
        "Floor, Boston, MA 02110-1301 USA.\n"
        "\n"
        "EXCEPTION NOTICE\n"
        "\n"
        "1. As a special exception, the copyright holders of this library give\n"
        "permission for additional uses of the text contained in this release of the\n"
        "library as licenced under the wxWindows Library Licence, applying either\n"
        "version 3.1 of the Licence, or (at your option) any later version of the\n"
        "Licence as published by the copyright holders of version 3.1 of the Licence\n"
        "document.\n"
        "\n"
        "2. The exception is that you may use, copy, link, modify and distribute\n"
        "under your own terms, binary object code versions of works based on the\n"
        "Library.\n"
        "\n"
        "3. If you copy code from files distributed under the terms of the GNU\n"
        "General Public Licence or the GNU Library General Public Licence into a\n"
        "copy of this library, as this licence permits, the exception does not apply\n"
        "to the code that you add in this way.  To avoid misleading anyone as to the\n"
        "status of such modified files, you must delete this exception notice from\n"
        "such code and/or adjust the licensing conditions notice accordingly.\n"
        "\n"
        "4. If you write modifications of your own for this library, it is your\n"
        "choice whether to permit this exception to apply to your modifications.  If\n"
        "you do not wish that, you must delete the exception notice from such code\n"
        "and/or adjust the licensing conditions notice accordingly.";
