// Copyright 2020 Allan Riordan Boll

#ifndef SRC_IDS_H_
#define SRC_IDS_H_

#define ID_SET_DIR 10
#define ID_PARENT_DIR 20
#define ID_SHOW_LICENSES 30
#define ID_OPEN_SELECTED 40
#define ID_DOWNLOAD 50
#define ID_UPLOAD 60
#define ID_CANCEL 70
#define ID_RENAME 80
#define ID_MKDIR 90
#define ID_SUDO 100

#define ID_SFTP_THREAD_RESPONSE_CONNECTED 510
#define ID_SFTP_THREAD_RESPONSE_GET_DIR 520
#define ID_SFTP_THREAD_RESPONSE_NEED_PASSWD 530
#define ID_SFTP_THREAD_RESPONSE_NEED_FINGERPRINT_APPROVAL 540
#define ID_SFTP_THREAD_RESPONSE_ERROR_AUTH 550
#define ID_SFTP_THREAD_RESPONSE_UPLOAD 560
#define ID_SFTP_THREAD_RESPONSE_ERROR_CONNECTION 570
#define ID_SFTP_THREAD_RESPONSE_DOWNLOAD 580
#define ID_SFTP_THREAD_RESPONSE_DOWNLOAD_FAILED 590
#define ID_SFTP_THREAD_RESPONSE_DOWNLOAD_FAILED_PERMISSION 600
#define ID_SFTP_THREAD_RESPONSE_UPLOAD_FAILED 610
#define ID_SFTP_THREAD_RESPONSE_PERMISSION 620
#define ID_SFTP_THREAD_RESPONSE_UPLOAD_FAILED_SPACE 630
#define ID_SFTP_THREAD_RESPONSE_DIR_ALREADY_EXISTS 640
#define ID_SFTP_THREAD_RESPONSE_DIR_LIST_FAILED 650
#define ID_SFTP_THREAD_RESPONSE_FILE_NOT_FOUND 660
#define ID_SFTP_THREAD_RESPONSE_CONFIRM_OVERWRITE 670
#define ID_SFTP_THREAD_RESPONSE_CANCELLED 680
#define ID_SFTP_THREAD_RESPONSE_SUCCESS 690
#define ID_SFTP_THREAD_RESPONSE_DELETE_FAILED 700
#define ID_SFTP_THREAD_RESPONSE_DELETE_SUCCEEDED 710
#define ID_SFTP_THREAD_RESPONSE_FOLLOW_SYMLINK_DIR 720
#define ID_SFTP_THREAD_RESPONSE_GO_TO 730
#define ID_SFTP_THREAD_RESPONSE_SUDO_NEEDS_PASSWD 740
#define ID_SFTP_THREAD_RESPONSE_SUDO_SUCCEEDED 750
#define ID_SFTP_THREAD_RESPONSE_SUDO_FAILED 760
#define ID_SFTP_THREAD_RESPONSE_SUDO_EXIT_SUCCEEDED 770
#define ID_SFTP_THREAD_RESPONSE_UPLOAD_PROGRESS 780
#define ID_SFTP_THREAD_RESPONSE_DOWNLOAD_PROGRESS 790


#endif  // SRC_IDS_H_
